## Preprocessing

In [17]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [19]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df= application_df.drop(['EIN'],1)
application_df

<ipython-input-19-3f2fc92c2ac7>:2: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df= application_df.drop(['EIN'],1)

,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...,...
34294,THE LIONS CLUB OF HONOLULU KAMEHAMEHA,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,INTERNATIONAL ASSOCIATION OF LIONS CLUBS,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,PTA HAWAII CONGRESS,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,AMERICAN FEDERATION OF GOVERNMENT EMPLOYEES LO...,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,WATERHOUSE CHARITABLE TR,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [20]:
# Determine the number of unique values in each column.
application_df.nunique()

NAME                      19568
APPLICATION_TYPE             17
AFFILIATION                   6
CLASSIFICATION               71
USE_CASE                      5
ORGANIZATION                  4
STATUS                        2
INCOME_AMT                    9
SPECIAL_CONSIDERATIONS        2
ASK_AMT                    8747
IS_SUCCESSFUL                 2
dtype: int64

In [24]:
#Look at NAME value counts for binning
name_counts= application_df['NAME'].value_counts()
# How many name counts are > 5
name_counts[name_counts>5]

PARENT BOOSTER USA INC                             1260
TOPS CLUB INC                                       765
UNITED STATES BOWLING CONGRESS INC                  700
WASHINGTON STATE UNIVERSITY                         492
AMATEUR ATHLETIC UNION OF THE UNITED STATES INC     408
                                                   ...
OLD OAK CLIFF CONSERVATION LEAGUE INC                 6
AMERICAN NEPHROLOGY NURSES ASSOCIATION                6
HUMBLE ISD EDUCATIONAL SUPPORT GROUPS INC             6
PROFESSIONAL LOADMASTER ASSOCIATION                   6
CBMC INC                                              6
Name: NAME, Length: 354, dtype: int64

In [25]:
#Determine values to replace when count < =5
names_to_replace =list(name_counts[name_counts <=5].index)
#Replace in dataframe
for app in names_to_replace:
  application_df['NAME'] = application_df['NAME'].replace(app,"Other")

#Check to make sure bining was successful
application_df['NAME'].value_counts()

Other                                           20043
PARENT BOOSTER USA INC                           1260
TOPS CLUB INC                                     765
UNITED STATES BOWLING CONGRESS INC                700
WASHINGTON STATE UNIVERSITY                       492
                                                ...
HABITAT FOR HUMANITY INTERNATIONAL                  6
DAMAGE PREVENTION COUNCIL OF TEXAS                  6
FLEET RESERVE ASSOCIATION                           6
HUGH OBRIAN YOUTH LEADERSHIP                        6
INTERNATIONAL CONGRESS OF CHURCHES MINISTERS        6
Name: NAME, Length: 355, dtype: int64

In [26]:
# Look at APPLICATION_TYPE value counts for binning
applic_valcount= application_df['APPLICATION_TYPE'].value_counts()
applic_valcount

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [30]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = applic_valcount[applic_valcount < 500 ].index

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: APPLICATION_TYPE, dtype: int64

In [32]:
# Look at CLASSIFICATION value counts for binning
classific_count =application_df['CLASSIFICATION'].value_counts()
classific_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classific_count[classific_count >1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [33]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classific_count[classific_count < 1000].index

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [34]:
# Convert categorical data to numeric with `pd.get_dummies`
num_df = pd.get_dummies(application_df)
num_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,NAME_AACE INTERNATIONAL,NAME_ACE MENTOR PROGRAM OF AMERICA INC,NAME_AFRICAN-AMERICAN POSTAL LEAGUE UNITED FOR SUCCESS A-PLUS,NAME_AIR FORCE ASSOCIATION,NAME_ALABAMA FEDERATION OF WOMENS CLUBS,NAME_ALABAMA TREASURE FOREST ASSOCIATION,NAME_ALBANY STATE UNIVERSITY NATIONAL ALUMNI ASSOCIATION,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [35]:
# Split our preprocessed data into our features and target arrays
y=num_df["IS_SUCCESSFUL"].values
X= num_df.drop(["IS_SUCCESSFUL"], axis='columns').values
# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=78)

In [36]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [37]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE

nn = tf.keras.models.Sequential()
input_dimension =len(X_train[0])
# First hidden layer
nn.add(tf.keras.layers.Dense(units=100, activation = 'relu',input_dim=input_dimension ))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation ='sigmoid'))

#Third hidden layer
nn.add(tf.keras.layers.Dense(units=10, activation= 'sigmoid'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# Check the structure of the model
nn.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_4 (Dense)             (None, 100)               39600

 dense_5 (Dense)             (None, 30)                3030

 dense_6 (Dense)             (None, 10)                310

 dense_7 (Dense)             (None, 1)                 11

=================================================================
Total params: 42951 (167.78 KB)
Trainable params: 42951 (167.78 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [38]:
# Compile the model
nn.compile(loss= "binary_crossentropy", optimizer = "adam", metrics =["accuracy"])

In [39]:
# Train the model
nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
804/804 [==============================] - 2s 2ms/step - loss: 0.4992 - accuracy: 0.7670
Epoch 2/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4443 - accuracy: 0.7936
Epoch 3/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4353 - accuracy: 0.7961
Epoch 4/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4308 - accuracy: 0.7966
Epoch 5/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4282 - accuracy: 0.7973
Epoch 6/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4263 - accuracy: 0.7979
Epoch 7/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4240 - accuracy: 0.7989
Epoch 8/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4232 - accuracy: 0.7984
Epoch 9/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4220 - accuracy: 0.7998
Epoch 10/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4208 - accuracy: 0.7992
Epoch 11/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.8000
Epoch 12/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4194 - accuracy: 0.8000
Epoch 13/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4185 - accuracy: 0.8012
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4180 - accuracy: 0.8015
Epoch 15/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4170 - accuracy: 0.8022
Epoch 16/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4167 - accuracy: 0.8012
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4157 - accuracy: 0.8022
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4162 - accuracy: 0.8010
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4156 - accuracy: 0.8017
Epoch 20/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4147 - accuracy: 0.8024
Epoch 21/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4135 - accuracy: 0.8029
Epoch 22/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4137 - accuracy: 0.8029
Epoch 23/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4131 - accuracy: 0.8038
Epoch 24/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4130 - accuracy: 0.8032
Epoch 25/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4120 - accuracy: 0.8032
Epoch 26/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4120 - accuracy: 0.8040
Epoch 27/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4111 - accuracy: 0.8043
Epoch 28/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4110 - accuracy: 0.8051
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8042
Epoch 30/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4103 - accuracy: 0.8046
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4096 - accuracy: 0.8053
Epoch 32/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4094 - accuracy: 0.8049
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4090 - accuracy: 0.8047
Epoch 34/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4089 - accuracy: 0.8053
Epoch 35/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4086 - accuracy: 0.8056
Epoch 36/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4083 - accuracy: 0.8059
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4082 - accuracy: 0.8057
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4080 - accuracy: 0.8056
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4077 - accuracy: 0.8056
Epoch 40/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4076 - accuracy: 0.8059
Epoch 41/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4073 - accuracy: 0.8060
Epoch 42/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4069 - accuracy: 0.8067
Epoch 43/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4064 - accuracy: 0.8066
Epoch 44/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4068 - accuracy: 0.8064
Epoch 45/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4066 - accuracy: 0.8056
Epoch 46/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4061 - accuracy: 0.8074
Epoch 47/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4060 - accuracy: 0.8071
Epoch 48/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4058 - accuracy: 0.8075
Epoch 49/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4057 - accuracy: 0.8075
Epoch 50/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4064 - accuracy: 0.8068
Epoch 51/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4057 - accuracy: 0.8069
Epoch 52/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4056 - accuracy: 0.8073
Epoch 53/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4052 - accuracy: 0.8064
Epoch 54/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4054 - accuracy: 0.8068
Epoch 55/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4049 - accuracy: 0.8071
Epoch 56/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4048 - accuracy: 0.8073
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4047 - accuracy: 0.8072
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4050 - accuracy: 0.8073
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4046 - accuracy: 0.8068
Epoch 60/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4046 - accuracy: 0.8072
Epoch 61/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4043 - accuracy: 0.8073
Epoch 62/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4042 - accuracy: 0.8070
Epoch 63/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4041 - accuracy: 0.8064
Epoch 64/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4040 - accuracy: 0.8082
Epoch 65/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4039 - accuracy: 0.8080
Epoch 66/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8070
Epoch 67/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4036 - accuracy: 0.8071
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4040 - accuracy: 0.8077
Epoch 69/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4037 - accuracy: 0.8084
Epoch 70/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4038 - accuracy: 0.8066
Epoch 71/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4036 - accuracy: 0.8077
Epoch 72/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8074
Epoch 73/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4033 - accuracy: 0.8073
Epoch 74/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4034 - accuracy: 0.8080
Epoch 75/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4032 - accuracy: 0.8084
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4030 - accuracy: 0.8071
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4029 - accuracy: 0.8077
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4032 - accuracy: 0.8085
Epoch 79/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8073
Epoch 80/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4028 - accuracy: 0.8083
Epoch 81/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4028 - accuracy: 0.8075
Epoch 82/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4026 - accuracy: 0.8075
Epoch 83/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4026 - accuracy: 0.8071
Epoch 84/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4026 - accuracy: 0.8087
Epoch 85/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4023 - accuracy: 0.8084
Epoch 86/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4031 - accuracy: 0.8076
Epoch 87/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4024 - accuracy: 0.8086
Epoch 88/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8081
Epoch 89/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4023 - accuracy: 0.8083
Epoch 90/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4026 - accuracy: 0.8079
Epoch 91/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8085
Epoch 92/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4022 - accuracy: 0.8086
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.4023 - accuracy: 0.8085
Epoch 94/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4027 - accuracy: 0.8081
Epoch 95/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4021 - accuracy: 0.8085
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4018 - accuracy: 0.8088
Epoch 97/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4017 - accuracy: 0.8090
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4021 - accuracy: 0.8084
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4017 - accuracy: 0.8075
Epoch 100/100
804/804 [==============================] - 1s 1ms/step - loss: 0.4021 - accuracy: 0.8084

In [40]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.4466 - accuracy: 0.7903 - 289ms/epoch - 1ms/step
Loss: 0.4466320872306824, Accuracy: 0.7903206944465637

In [42]:
# Export our model to HDF5 file
nn.save('Files/AlphabetSoupCharity_Optimization.h5')

In [43]:
from google.colab import files
model_name = "AlphabtetSoupCharity_Optimization.h5"
nn.save(model_name)
files.download(model_name)